version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencie...
      - apt-get update
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon beanstalk...
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean install
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon beansTalk...
